definitions:
  config:
    /hippo:namespaces/alligator/product:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: bac78774-9fc4-4fc6-9aa5-b12753df5919
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: a029c73c-b816-458c-8e84-10232ae1e32b
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          jcr:uuid: 23ff5f4c-8bab-4e6a-ab0a-d0bc74753574
          hipposysedit:node: true
          hipposysedit:supertype: ['alligator:basedocument', 'hippostd:relaxed', 'hippotranslation:translated']
          hipposysedit:uri: http://www.alligator.com/alligator/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: alligator:title
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [required]
          /price:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: alligator:price
            hipposysedit:primary: false
            hipposysedit:type: Double
            hipposysedit:validators: [required]
          /introduction:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: alligator:introduction
            hipposysedit:primary: false
            hipposysedit:type: Text
            hipposysedit:validators: [required]
          /description:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: alligator:description
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
            hipposysedit:validators: [required]
          /images:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: false
            hipposysedit:path: alligator:images
            hipposysedit:primary: false
            hipposysedit:type: hippogallerypicker:imagelink
            hipposysedit:validators: [required]
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: alligator:product
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          jcr:mixinTypes: ['mix:referenceable']
          alligator:title: ''
          alligator:price: 0.0
          alligator:introduction: ''
          jcr:uuid: 29a4dbca-6fac-4bfc-8745-a6d12aa2f42b
          hippostdpubwf:lastModificationDate: 2019-10-23T15:35:51.176+02:00
          hippostdpubwf:creationDate: 2019-10-23T15:35:51.177+02:00
          /alligator:description:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
          /alligator:images:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /title:
            jcr:primaryType: frontend:plugin
            caption: Title
            field: title
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /price:
            jcr:primaryType: frontend:plugin
            caption: Price
            field: price
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /introduction:
            jcr:primaryType: frontend:plugin
            caption: Introduction
            field: introduction
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /description:
            jcr:primaryType: frontend:plugin
            caption: Description
            field: description
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /images:
            jcr:primaryType: frontend:plugin
            caption: Images
            field: images
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
